### ISSUE TITLE
Album sorting is not working for the new redesign

### ISSUE THREAD

**Issue by froleo** [VipSaran/Google-Play-Music-Album-Sorter#1]
Album sorting does not seem to be working for the new redesign. Are you planning to update compability? This is a sorely needed feature, can't beleieve that it's not an official feature.

**Comment by VipSaran** [comment]
I've seen the redesign yesterday and I think there shouldn't be much problems with "porting" the sort functionality to this new design. I'll post here when it's done.

**Comment by VipSaran** [comment]
I've seen the redesign yesterday and I think there shouldn't be much problems with "porting" the sort functionality to this new design. I'll post here when it's done.

**Comment by rsodha** [comment]
Thanks for working on sorting feature. I have been looking for this since last few months. Hopefully you'll be able to get this working again.

**Comment by VipSaran** [comment]
Support for material design GPM sorted (pun intended!) with https://github.com/VipSaran/Google-Play-Music-Album-Sorter/releases/tag/1.1.1.
