### ISSUE TITLE
Google Play Music Site Update Seems to Have Broken Script Again

### ISSUE THREAD

**Issue by Jeremy-D-Miller** [VipSaran/Google-Play-Music-Album-Sorter#4]
Hi Robert,

It seems a recent update to the Google Play Music site has broken this script once more: http://imgur.com/LyPaFJl

I for one appreciate you keeping this up to date, and appreciate any further efforts to continue to do so when you have time.

Thanks,

-Jeremy

**Comment by Jeremy-D-Miller** [comment]
Upon closer inspection, I'm not sure what exactly going on... It seems the "main" albums are still in (reverse) order, but then there are dupes and addtional albums at the end of the list.  I'd appreciate it if you could verify when you have a chance.

-J

**Comment by VipSaran** [comment]
Thanks for reporting.

I've started fixing the script some weeks ago, but stopped in the middle due to some other commitments.

Can't promise when, but I'll get to it eventually. Thanks for the patience :)

**Comment by Jeremy-D-Miller** [comment]
No problem at all.  There seems to have been an influx of new metadata and/or duplication of albums but I'm sure they would just claim "we present it the same way it was given to us," le sigh.

**Comment by Jeremy-D-Miller** [comment]
The update looks good. Thanks for following up!
