### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by yodiyo** [VipSaran/Google-Play-Music-Album-Sorter#5]
Hi - this is a really nice idea but I can't get it to work. I'm using Chrome - here's the console output:
`content.js:25content: normal start event processing for 477f514f-3d29-4450-a1cb-f35d38a8de6c (1 to run)
content.js:12content: Start ENV normally 477f514f-3d29-4450-a1cb-f35d38a8de6c
VM7674:14env: initialized (content, id:477f514f-3..., https://play.google.com/music/listen) 
VM7674:65Tampermonkey started
VM7674:13env: schedule "Google Play Music Album Sorter" for document-end
sj_srcs.js:24967 This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead(anonymous function) @ sj_srcs.js:24967
sj_srcs.js:24968 This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead(anonymous function) @ sj_srcs.js:24968
content.js:10content: detected DOMContentLoaded 477f514f-3d29-4450-a1cb-f35d38a8de6c
VM7674:64env: execute script Google Play Music Album Sorter @ the safe context now!
sj_srcs.js:12834 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.attached @ sj_srcs.js:12834_invokeBehavior @ sj_srcs.js:443_doBehavior @ sj_srcs.js:431(anonymous function) @ sj_srcs.js:215_makeReady @ sj_srcs.js:103(anonymous function) @ sj_srcs.js:109(anonymous function) @ sj_srcs.js:10489
listen__en_gb.js:803 'webkitAudioContext' is deprecated. Please use 'AudioContext' instead.rE @ listen__en_gb.js:803BU @ listen__en_gb.js:1503d.ANa @ listen__en_gb.js:1513d.Ecb @ listen__en_gb.js:1513EU @ listen__en_gb.js:1511(anonymous function) @ listen__en_gb.js:3161d.cYa @ listen__en_gb.js:1515d.Cgb @ listen__en_gb.js:1515(anonymous function) @ listen__en_gb.js:1471c @ listen__en_gb.js:623
content.js:10content: detected DOMContentLoaded 477f514f-3d29-4450-a1cb-f35d38a8de6c`

**Comment by VipSaran** [comment]
Thanks @yodiyo for your feedback.

I have stopped development since Google has started pre-sorting albums (chronologically, in descending order).
